"""Web search tool backed by Google Search grounding in the Gemini API.

No extra search API or key is needed: the Gemini API runs the Google searches and returns
grounding metadata. Every returned URL comes from that metadata; nothing is generated by the
model. If search is disabled or grounding returns no sources, the tool says so instead of
inventing results.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from core.config import get_settings
from core.llm import grounded_search

PROVIDER = "Google Search grounding (Gemini API)"


class WebSearchUnavailable(RuntimeError):
    pass


class WebSearchInput(BaseModel):
    query: str = Field(description="Focused search query")
    max_results: int = Field(default=5, description="Maximum number of sources to return (1-8)")


class SearchResult(BaseModel):
    title: str
    url: str
    snippet: str
    source: str


class WebSearchOutput(BaseModel):
    query: str
    provider: str = PROVIDER
    search_queries: list[str]
    summary: str
    results: list[SearchResult]
    note: str = ""


def run(args: WebSearchInput, context: Any) -> WebSearchOutput:
    settings = get_settings()
    if not settings.web_search_enabled:
        raise WebSearchUnavailable(
            "Live web research is unavailable: web search is disabled (WEB_SEARCH_ENABLED=false). "
            "No sources were retrieved."
        )
    limit = max(1, min(args.max_results, settings.web_search_max_results, 8))
    grounded = grounded_search(args.query)
    context.record_llm_call(grounded.info)

    results: list[SearchResult] = []
    seen: set[str] = set()
    for idx, chunk in enumerate(grounded.chunks):
        url = chunk.get("url")
        if not url or url in seen:
            continue
        seen.add(url)
        snippet = " ".join(dict.fromkeys(grounded.chunk_snippets.get(idx, [])))[:400]
        results.append(SearchResult(
            title=chunk.get("title") or chunk.get("domain") or "Untitled",
            url=url,
            snippet=snippet,
            source=chunk.get("domain") or chunk.get("title") or "",
        ))
        if len(results) >= limit:
            break

    note = ""
    if not results:
        note = ("Search grounding returned no web sources for this query; the summary below is not "
                "source-backed and must not be cited.")
    return WebSearchOutput(
        query=args.query,
        search_queries=grounded.queries,
        summary=grounded.text[:4000],
        results=results,
        note=note,
    )
